package: passwordless_login
version: 0.0.1-dev
author: eaCe
supportpage: 'https://github.com/eaCe/passwordless_login'
requires:
    packages:
        phpmailer: ^2.0.0
    redaxo: ^5.12.0
    php:
        version: '>=7.4'
installer_ignore:
    - node_modules
    - .git
    - .gitignore
    - .github
    - package.json
    - yarn.lock
    - resources
    - .editorconfig
    - .eslintrc.js
    - .stylelintrc.js
    - .stylelintrc.js
    - composer.json
    - composer.lock
    - phpcs.xml
    - tests
    - .tools
secret: 92d894ea9517fdf47074f786b34661ebcf18643992205d319373f4f1215ebdf5
